# Generated by extendr: Do not edit by hand
#
# This file was created with the following call:
#   .Call("wrap__make_rparquet_wrappers", use_symbols = TRUE, package_name = "rparquet")

#' @docType package
#' @usage NULL
#' @useDynLib rparquet, .registration = TRUE
NULL

#' Return string `"Hello world!"` to R.
#' @export
hello_world <- function() .Call(wrap__hello_world)

parquet_read_schema <- function(path, schema_ptr) .Call(wrap__parquet_read_schema, path, schema_ptr)

